### ISSUE TITLE
Steam API Interface

### ISSUE THREAD

**Issue by gregorydwyer** [ProfileHUD-Team/ProfileHUD#1]
As a user, I need to be able to get information from the Steam API. 
It needs to be able to pull: Games Played, number(& names?) of achievements for each game, hours played for each game, steam profile img

**Comment by Favillar012** [comment]
I estimate that completing the Steam API stuff will take me about two weeks from today (give or take). It might take me less time but I can't say for sure.

**Comment by Favillar012** [comment]
I am nearly done with the SteamAPIConnector. More testing and handling of special cases is still required. I estimate that completing these additional requirements will take another 4 to 5 days.

**Comment by Favillar012** [comment]
I am finished with the SteamAPIConnector. All of the core functionality such as getting Steam users, their games, and achievements is fully implemented. Error cases are also handled. The only thing that was not implemented was getting images for Steam users, games, or achievements. This is something that I will go back and implement if time permits it.
